/** Shared label map for audit_logs.action values — used by both the flat AuditTrail and the vertical DocumentTimeline so the two never drift apart. */
export const ACTION_LABELS: Record<string, string> = {
  "document.generated": "Generated",
  "document.sent": "Sent",
  "document.viewed": "Viewed",
  "document.consent_accepted": "Consent accepted",
  "document.signed_by_employee": "Signed by employee",
  "document.signed_by_employer": "Signed by employer",
  "document.completed": "Completed",
  "document.downloaded": "Downloaded",
  "document.verified": "Verified",
  "document.deleted": "Deleted",
  "document.restored": "Restored",
  "employee.created": "Employee created",
  "employee.updated": "Employee updated",
  "employee.deleted": "Employee deleted",
  "template.created": "Template created",
  "template.updated": "Template updated",
  "template.deleted": "Template deleted",
  "document.uploaded_by_employee": "Uploaded by employee",
  "employee.registered": "Account requested",
  "employee.approved": "Account approved",
  "employee.rejected": "Account rejected",
  "tenant.invite_code_regenerated": "Invite link regenerated",
  "tenant.signatory_updated": "Signatory updated",
  "identity_document.uploaded": "ID document uploaded",
  "identity_document.verified": "ID document verified",
  "identity_document.rejected": "ID document rejected",
  "identity_document.expiry_reminder_sent": "Expiry reminder sent",
  "super_admin.tenant_plan_updated": "Plan changed",
  "super_admin.tenant_status_updated": "Tenant status changed",
  "super_admin.impersonation_started": "Support impersonation link generated",
  "gdpr.tenant_data_exported": "Data exported",
  "employee.anonymized": "Employee anonymized (GDPR erasure)",
  "audit_log.purged": "Audit log entries purged",
};
